### ISSUE TITLE
Image Clock Sync

### ISSUE THREAD

**Issue by JJBUT** [ut-amrl/spinnaker_ros_interface#2]
https://github.com/ut-amrl/spinnaker_ros_interface/blob/4765be4f31bcfd260862a25168f5ef5544afa0d4/src/spinnaker_ros_interface_main.cc#L268

@joydeep-b  (please correct me if I'm wrong) this gives the sensor topic published by each camera a timestamp that appears to be referenced to the time when you turned the camera on/started up the ROS interface. For practical purposes this isn't easy to work with because the image header stamps will then be in a completely different time reference frame. This make using a message synchronizer impossible and make the bag files more challenging to interpret in general.

Can we instead use [ros::Time](https://wiki.ros.org/roscpp/Overview/Time) to assign the header stamp here? Or some other method that will save us the trouble described above? I understand that we need to make it so that the image is labeled with the time it's acquired and not the time it gets published, but I think we can do this with some simple logic.

On the computer hardware side the NRG team has experience and recommend using [chrony](https://en.wikipedia.org/wiki/Chrony) for network timing/syncing issues with ROS. That way we can guarantee a consistent wall clock time across all platforms that ros::Time can consistently access to populate all message headers.

CC
@srabiee 

* Note i'm not sure if a GitHub issue was the best way to communicate in this case *

**Comment by joydeep-b** [comment]
Using ros:Time for timestamps is not accurate - that will report the time that the image is processed by the ROS wrapper, not the time of capture. The difference between the two is affected by:
1. Wire transfer time
2. Computer IO processing time
3. Processing time taken by the ROS wrapper program

Item 1 is usually very consistent and can be calibrated out, but 2 and 3 are subject to variations due to scheduler and image processing time variations. 
The hardware-reported timestamps is the most accurate for relative time measurements.
To convert the relative time stamps to wall time, you could estimate the clock offset at startup (e.g. using the difference between a high-resolution system clock and the first camera frame timestamp), and add that constant offset to all subsequent frames. That preserves the accurate relative timestamps, while providing a wall time for your needs. Feel free to make a PR with the offset estimation on startup.

Chrony / NTP is an orthogonal problem - you can sync computer times however you want.

**Comment by JJBUT** [comment]
The inaccuracy of using ros::Time in the wrapper is what I was trying to communicate when I wrote 

> I understand that we need to make it so that the image is labeled with the time it's acquired and not the time it gets published, but I think we can do this with some simple logic

I will look at making a PR when I get the time, what you describe is what I was thinking when I wrote "we can do this with some simple logic". Thanks for looking at this so quickly!

**Comment by JJBUT** [comment]
https://github.com/ut-amrl/spinnaker_ros_interface/pull/4
